### PR TITLE
Consider refresh token for cached results

### LINKED ISSUE #178: OAuth caching does not respect `refresh_token`
The caching does not respect the refresh token.

``` r
library(httr2)

client <- oauth_client("example", "https://example.com/get_token")
req <- request("https://example.com")

# create 2 requests with different refresh token
req1 <- req %>% 
  req_oauth_refresh(client, refresh_token = "rt1")
req2 <- req %>% 
  req_oauth_refresh(client, refresh_token = "rt2")

# simulate that we made a request and got back a token
token <- oauth_token(
  access_token = "a",
  token_type = "bearer",
  expires_in = NULL,
  refresh_token = "rt1",
  .date = Sys.time()
)
# ... that is now cached
req1$policies$auth_oauth$cache$set(token)
req1$policies$auth_oauth$cache$get() %>% str()
#> List of 3
#>  $ token_type   : chr "bearer"
#>  $ access_token : chr "a"
#>  $ refresh_token: chr "rt1"
#>  - attr(*, "class")= chr "httr2_token"
# but also in req2
req2$policies$auth_oauth$cache$get() %>% str()
#> List of 3
#>  $ token_type   : chr "bearer"
#>  $ access_token : chr "a"
#>  $ refresh_token: chr "rt1"
#>  - attr(*, "class")= chr "httr2_token"

# or shown in `auth_oauth_sign()` which is used in `req_perform()`
req1 %>% 
  httr2:::auth_oauth_sign() %>% 
  print(redact_headers = FALSE)
#> <httr2_request>
#> GET https://example.com
#> Headers:
#> • Authorization: 'Bearer a'
#> Body: empty
#> Policies:
#> • auth_oauth: a list

req2 %>% 
  httr2:::auth_oauth_sign() %>% 
  print(redact_headers = FALSE)
#> <httr2_request>
#> GET https://example.com
#> Headers:
#> • Authorization: 'Bearer a'
#> Body: empty
#> Policies:
#> • auth_oauth: a list
```

<sup>Created on 2022-10-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### PR DESCRIPTION
**Pull request by mgirlich**
Fixes #178.
@hadley The same might need to be done in

* `req_oauth_client_credentials()` (with `token_params`)
* `req_oauth_bearer_jwt()`

but I don't know much about OAuth so maybe you know this better.

### CODE REVIEW

**Comment by hadley** [comment]
Yeah, I think this is right, and we need to think about the cache keys in those other functions.

**Comment by jennybc** [comment]
@Hadley What are the ambitions here? On the spectrum of "let's take known progress on `req_oauth_refresh()`" to "let's rationalize cache keys for all flows".

**Comment by hadley** [comment]
I'd say let's merge this PR, but open an issue to remind me/you to look at `req_oauth_client_credentials()`/`req_oauth_bearer_jwt()` the next time either of us has sufficient context loaded in our brains.

**Comment by mgirlich** [comment]
@jennybc Are you fine with merging this? 😄

**Review by jennybc — APPROVED** [review]
With the caveat that it's been a while since I thought about it, yes, I'm happy to merge and I'm glad you opened the issue to remind us to think about related issues elsewhere.

I'll sort out the `NEWS.md` conflict and approve, leaving @Hadley to do the actual merge.

**Pull request merged**
